// Generated by jextract

package com.github.tjake.jlama.tensor.operations.cnative;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class Constants$root {

    // Suppresses default constructor, ensuring non-instantiability.
    private Constants$root() {}
    static final OfBoolean C_BOOL$LAYOUT = JAVA_BOOLEAN;
    static final OfByte C_CHAR$LAYOUT = JAVA_BYTE;
    static final OfShort C_SHORT$LAYOUT = JAVA_SHORT;
    static final OfInt C_INT$LAYOUT = JAVA_INT;
    static final OfLong C_LONG$LAYOUT = JAVA_LONG;
    static final OfLong C_LONG_LONG$LAYOUT = JAVA_LONG;
    static final OfFloat C_FLOAT$LAYOUT = JAVA_FLOAT;
    static final OfDouble C_DOUBLE$LAYOUT = JAVA_DOUBLE;
    static final OfAddress C_POINTER$LAYOUT = ADDRESS.withBitAlignment(64).asUnbounded();
}


